### ISSUE TITLE
Merge with 9820 kernel source / ASOP kernel source?

### ISSUE THREAD

**Issue by francoism90** [pakaoraki/android_kernel_samsung_universal9810#1]
Hi Pakaoraki,

Thanks for maintaining this phone. I'm using a fork and will checkout changes you've made in your repo's. :)

I just wanted to let you know the 9820 kernel seems to have references to 9810:
<https://github.com/LineageOS/android_kernel_samsung_exynos9820/search?q=9810&type=code>

I've tried compiling it with changes made to _Kconfig_ and some other inclusions, unfortunately it didn't compile as still some things seems to be missing.

Maybe merging (some things of) the ASOP kernel would be possible?

**Comment by pakaoraki** [comment]
Hi François,

I'm glad if my repo can be useful for you. I'm I not really the dev
behind this code, I just want to build the most stable/updated build for
my Galaxy S9 phone. Two years ago, my device was officially supported by
Lineageos project but the person(s) who maintained the build stop. Since
then, I found an unofficial build made by *synt4x93* (*Rob*) on XDA
forum. He just made one build last year, so me and some others guys
start doing our own build based on his code, and I sign it with my
personal certificate. He didn't publish any new build but sometimes he
update some code on his Github repo. I upload my build on Github for OTA
and make also available for other people that can't compile themself.

What I'm doing is mixing last commits from *synt4x93* and the last
*Kernel for exynos 9810 4.9.290* up to date from *Geoknyda*. I just want
to have a functional phone on Lineageos 18.1 with the last security
patch from Google and code update from Lineageos. Plus, *Geoknyda*
included /WireGuard/ module in his kernel. In the future, I plan to use
the kernel from *Krazey* that is more recent, but from now my test build
doesn't boot with it, I have to figure out what's wrong.

Apart of that, I am just a bash/linux/IT enthusiast but I'm not a
confirmed android dev and I am still learning and discovering it. So to
be honest, I will not be really helpful on technical questions about
android code.

It's seems that you want to compile Lineage for Exynos 9820 (Galaxy S10
maybe ?), I personally don't think you need to add the 9810 Kernel to
your sources, it should be ok just using the Lineage repo as the S10 is
officially supported. Maybe try to compile with a docker image :

  * mine: https://hub.docker.com/r/pakaoraki/docker-lineage-cicd
  * Or this one:
    https://hub.docker.com/r/lineageos4microg/docker-lineage-cicd.

Otherwise, you should contact the dev that works on your device or try
to ask for help on XDA forum. Sorry that I can't really help you more.


*_Sources__:_*

  * *synt4x93 ***original post for S9 on *XDA forum:*
    _https://forum.xda-developers.com/t/rom-s9-s9-unofficial-lineageos-18-1-21-03-2021.4203777/
    _
  * *synt4x93 Github repo:*
      o Kernel 9810:
        https://github.com/synt4x93/android_kernel_samsung_universal9810
      o Device universal 9810:
        https://github.com/synt4x93/android_device_samsung_universal9810-common
      o Device S9:
        https://github.com/synt4x93/android_device_samsung_starlte
  * *Geoknyda/Neurotical S9 XDA Forum*:
    https://forum.xda-developers.com/t/rom-s9-s9-unofficial-lineageos-18-1-exynos-weekly.4302901/
  * *Geoknyda/Neurotical Github*:
      o Kernel 9810:
        https://github.com/Geoknyda/android_kernel_samsung_universal9810
      o Device universal 9810:
        https://github.com/Geoknyda/android_device_samsung_universal9810-common
  * *Krazey Github (for the last kernel)*:
    https://github.com/krazey/android_kernel_samsung_exynos9810/tree/android-4.11-r



We can exchange in french if you want to.


Cheers,


Stéphane (Pakaoraki)
